name: .NET Core 6.0.x

on:
  push:
    branches: [master]
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies Calabonga.RulesValidator
        run: dotnet restore src/Calabonga.RulesValidator/Calabonga.RulesValidator.sln

      - name: Build the NuGet package Calabonga.RulesValidator
        run: dotnet build src/Calabonga.RulesValidator/Calabonga.RulesValidator.sln --configuration Release --output ${{env.DOTNET_ROOT}}\Package1
        
      - name: Publish NuGet Package Calabonga.RulesValidator
        run: dotnet nuget push ${{env.DOTNET_ROOT}}\Package1\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
      - name: Install dependencies Calabonga.RulesValidator.AspNetCore
        run: dotnet restore src/Calabonga.RulesValidator.AspNetCore/Calabonga.RulesValidator.AspNetCore.sln

        
      - name: Build the NuGet package Calabonga.RulesValidator
        run: dotnet build src/Calabonga.RulesValidator.AspNetCore/Calabonga.RulesValidator.AspNetCore.sln --configuration Release --output ${{env.DOTNET_ROOT}}\Package2
        
      - name: Publish NuGet Package Calabonga.RulesValidator.AspNetCore
        run: dotnet nuget push ${{env.DOTNET_ROOT}}\Package2\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate